name: C/C++ Multi-Platform CI

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install Ninja
        run: choco install ninja
      - name: Install dependencies
        run: vcpkg install nlohmann-json:x64-windows
      - name: Configure CMake
        run: cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
      - name: Build
        run: cmake --build build --config Release

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: brew install nlohmann-json
      - name: Create build directory
        run: mkdir build
      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
      - name: Build macOS
        run: cmake --build build
      - name: Upload macOS Binary
        uses: actions/upload-artifact@v4
        with:
          name: game-macos
          path: build/game

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake nlohmann-json3-dev
      - name: Create build directory
        run: mkdir build
      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
      - name: Build Linux
        run: cmake --build build
      - name: Upload Linux Binary
        uses: actions/upload-artifact@v4
        with:
          name: game-linux
          path: build/game

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake nlohmann-json3-dev
      - name: Cache CMake build
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-cmake-test-${{ hashFiles('**/CMakeLists.txt', 'src/**', 'tests/**') }}
          restore-keys: |
            ${{ runner.os }}-cmake-test-
      - name: Create build directory
        run: mkdir build
      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON  -DCMAKE_CXX_FLAGS="-fsanitize=address -g"
      - name: Build Tests
        run: cmake --build build
      - name: Run Tests
        run: build/runTests
